---
title: "Lab08"
author: "Erica Goto"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LAB 08


Libraries:

```{r library, message=FALSE}

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
library(corrplot)



```


### Column graph of Texas oil spills:

```{r oil_spill, message="FALSE"}

oil_spills <- read_csv("oil_spills.csv")


df <- oil_spills %>% 
  filter(`Accident State` =="TX"& `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
summarise (Loss = sum(`Net Loss (Barrels)`))


colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x=Year, y=Loss)) +
         geom_col()




```

```{r}
df_loc <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)


colnames (df_loc) <- c("lat", "long", "net_loss")


oil_sf <- st_as_sf(df_loc, coords = c("long", "lat"), crs=4326)


leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()



```

## tmap plot with the Texas state shapefile

```{r}


states <- st_read(dsn=".", layer="states")

tex_border <- states %>% 
  filter (STATE_NAME == "Texas") %>% 
  st_transform(4326)


plot(tex_border) 


tm_shape (tex_border) + 
  tm_polygons() +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)



```


### Convert the data to spatial points patterns (combination of point data and the bounding window)

```{r ppp}
spill_sp <- as(oil_sf, "Spatial")
spill_ppp <- as(spill_sp, "ppp")


tx_sp <- as(tex_border, "Spatial")
tx_owin <- as(tx_sp, "owin")


all_ppp <- ppp( spill_ppp$x, spill_ppp$y, window=tx_owin)


```
## Plot
```{r}
plot(density(all_ppp, sigma=0.3)) ### you need to find  i meaniful way to use the sigma
```


### Quadrant test for spatial eveness
```{r oil_points}
oil_qt <- quadrat.test(all_ppp, nx=5, ny=5)

oil_qt # data are not evanly distributed

plot(all_ppp)
plot (oil_qt, add = TRUE, cex =0.4)
```


### G- Function for nearest neighbor analysis

```{r}
r <- seq(0,1, by=0.01)

oil_gfun <- envelope (all_ppp, fun = Gest, r = r, nsim = 100)

ggplot(oil_gfun, aes(x=r, y=obs)) + 
  geom_line(color="black") +
  geom_line(aes(x=r, y=theo), color = "red")+
  theme_bw()

```


### Nearest neighbor using the L-function (Ripley's K, standardized)
```{r}
r2 <- seq(0,3, by=0.5) # large increment because time cosuming in the lab... 
oil_lfun <- envelope (all_ppp, fun=Lest, r=r2, nsim = 20, global = TRUE) ### global = TRUE to include all observation

```

